const {
    saveMedia,
    getMedia,
    searchMedia,
    getMediaById,
    deleteMedia,
    addTag,
    removeTag,
    updateDescription,
    getMediaCount,
    markDeleted,
    MAX_MEDIA_PER_USER
} = require('../src/utils/mediaUtil');

describe('Media Utility', () => {
    describe('Module Exports', () => {
        test('should export all required functions', () => {
            expect(typeof saveMedia).toBe('function');
            expect(typeof getMedia).toBe('function');
            expect(typeof searchMedia).toBe('function');
            expect(typeof getMediaById).toBe('function');
            expect(typeof deleteMedia).toBe('function');
            expect(typeof addTag).toBe('function');
            expect(typeof removeTag).toBe('function');
            expect(typeof updateDescription).toBe('function');
            expect(typeof getMediaCount).toBe('function');
            expect(typeof markDeleted).toBe('function');
        });

        test('should export MAX_MEDIA_PER_USER constant', () => {
            expect(MAX_MEDIA_PER_USER).toBeDefined();
            expect(typeof MAX_MEDIA_PER_USER).toBe('number');
            expect(MAX_MEDIA_PER_USER).toBe(500);
        });
    });

    describe('Function Signatures', () => {
        test('saveMedia should accept metadata object', () => {
            expect(saveMedia.length).toBe(1);
        });

        test('getMedia should accept userId and optional options', () => {
            expect(getMedia.length).toBeGreaterThanOrEqual(1);
        });

        test('searchMedia should accept userId, query, and optional options', () => {
            expect(searchMedia.length).toBeGreaterThanOrEqual(2);
        });

        test('getMediaById should accept userId and mediaId', () => {
            expect(getMediaById.length).toBe(2);
        });

        test('deleteMedia should accept userId and mediaId', () => {
            expect(deleteMedia.length).toBe(2);
        });

        test('addTag should accept mediaId, tag, and optional autoGenerated flag', () => {
            expect(addTag.length).toBeGreaterThanOrEqual(2);
        });

        test('removeTag should accept mediaId and tag', () => {
            expect(removeTag.length).toBe(2);
        });

        test('updateDescription should accept userId, mediaId, and description', () => {
            expect(updateDescription.length).toBe(3);
        });

        test('getMediaCount should accept userId', () => {
            expect(getMediaCount.length).toBe(1);
        });

        test('markDeleted should accept messageId', () => {
            expect(markDeleted.length).toBe(1);
        });
    });

    describe('Documentation and Structure', () => {
        test('all exported functions should be defined', () => {
            const functions = [
                saveMedia,
                getMedia,
                searchMedia,
                getMediaById,
                deleteMedia,
                addTag,
                removeTag,
                updateDescription,
                getMediaCount,
                markDeleted
            ];

            functions.forEach(fn => {
                expect(fn).toBeDefined();
                expect(typeof fn).toBe('function');
            });
        });

        test('MAX_MEDIA_PER_USER should be reasonable', () => {
            expect(MAX_MEDIA_PER_USER).toBeGreaterThan(0);
            expect(MAX_MEDIA_PER_USER).toBeLessThanOrEqual(1000);
        });
    });

    describe('Tag Normalization', () => {
        test('tag functions should accept string tags', () => {
            // Basic structure test - actual normalization happens in implementation
            expect(() => addTag(1, 'test-tag', false)).not.toThrow();
            expect(() => removeTag(1, 'test-tag')).not.toThrow();
        });
    });

    describe('Metadata Structure', () => {
        test('saveMedia should accept comprehensive metadata', () => {
            const metadata = {
                userId: '123456789',
                guildId: '987654321',
                channelId: '111222333',
                messageId: '444555666',
                mediaUrl: 'https://cdn.discordapp.com/attachments/test.png',
                fileName: 'test.png',
                fileType: 'image',
                mimeType: 'image/png',
                fileSize: 1024000,
                width: 1920,
                height: 1080,
                duration: null,
                contentPreview: 'Test message',
                authorId: '123456789',
                captureMethod: 'auto'
            };

            // Should not throw with valid metadata
            expect(() => saveMedia(metadata)).not.toThrow();
        });
    });

    describe('Options Handling', () => {
        test('getMedia should handle filter options', () => {
            const options = {
                limit: 10,
                offset: 0,
                fileType: 'image',
                channelId: '123456',
                tags: ['test', 'demo'],
                sortBy: 'date'
            };

            // Should not throw with valid options
            expect(() => getMedia('123456789', options)).not.toThrow();
        });

        test('searchMedia should handle search options', () => {
            const options = {
                limit: 10,
                offset: 0
            };

            // Should not throw with valid query
            expect(() => searchMedia('123456789', 'test query', options)).not.toThrow();
        });
    });
});
